name=DevLab_BMI323
version=1.0.0
author=Adrian Rabadan Ortiz
maintainer=Adrian Rabadan Ortiz
sentence=Arduino library for Bosch BMI323 IMU using direct I2C register access.
paragraph=DevLab BMI323 library for accelerometer, gyroscope, and temperature acquisition using direct 16-bit register communication over I2C.
category=Sensors
url=https://github.com/UNIT-Electronics-MX/DevLab_BMI323
architectures=*
includes=DevLab_BMI323.h