name=DevLab_BMI323
version=1.0.1
author=Adrian Rabadan Ortiz, Jonathan Mejorado Lopez
maintainer=Adrian Rabadan Ortiz, Jonathan Mejorado Lopez 
sentence=Arduino library for Bosch BMI323 IMU using direct I2C register access.
paragraph=DevLab BMI323 library for accelerometer, gyroscope, and temperature acquisition using direct 16-bit register communication over I2C and SPI.
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_library_devlab_bmi323
architectures=*
includes=DevLab_BMI323.h
